version: "3.7"

services:
  elastic:
      image: "docker.elastic.co/elasticsearch/elasticsearch:8.7.1"
      container_name: elastic
      environment:
          - "discovery.type=single-node"
          - "xpack.security.enabled=false"
      ports:
          - "9200:9200"
      volumes:
          - ./vol/elastic:/usr/share/elasticsearch/data

  kibana:
      image: "docker.elastic.co/kibana/kibana:8.7.1"
      container_name: kibana
      ports:
          - "5601:5601"
      environment:
          - ELASTICSEARCH_HOSTS:http://elastic:9200
      depends_on:
          - elastic

  filebeat:
      build:
          context: ./docker/filebeat
      container_name: filebeat
      volumes:
          - ./vol/filebeat:/logs
      depends_on:
          - elastic
          - kibana

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bvi
    ports:
      - "5432:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./database_backup.sql:/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./vol/filebeat:/app/storage/logs

    depends_on:
      db:
        condition: service_healthy
